# Generated by Django 4.1.3 on 2022-11-25 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="team",
            old_name="top_score",
            new_name="top_scorer",
        ),
    ]
